# Generated by Django 4.2.3 on 2023-07-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='bookstatus',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='chaptercomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='chaptercomment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='chaptercommentlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='chaptercommentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='book',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quotecomment',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quotecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='books',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookStatus',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='ChapterComment',
        ),
        migrations.DeleteModel(
            name='ChapterCommentLike',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Overview',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteComment',
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
