# Generated by Django 4.2.3 on 2023-08-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='order_id',
        ),
        migrations.AddField(
            model_name='book',
            name='epub',
            field=models.FileField(blank=True, null=True, upload_to='epub/'),
        ),
    ]
